name: CI

on:
  pull_request:
   branches: 
      main
  push:
   branches:
      main

jobs:
  build:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        working-directory: ./social-media-app
        run: npm install

      - name: Run lint
        working-directory: ./social-media-app
        run: npm run lint

      - name: Run tests
        working-directory: ./social-media-app
        run: npm test
      
      - name: Run tests with coverage
        working-directory: ./social-media-app
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: social-media-app/coverage/

      - name: Build project
        working-directory: ./social-media-app
        run: npm run build

      - name: Upload production build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: social-media-app/build/
  
  deploy:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./social-media-app/build