name: CI

on:
  pull_request:
   branches: 
      main
  push:
   branches:
      main

jobs:
  build:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        run: | 
          cd social-media-app 
          npm install

      - name: Run tests
        run: | 
          cd social-media-app
          npm test

      - name: Build project
        run: | 
          cd social-media-app
          npm run build

      - name: Upload production build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: social-media-app/build/
